config/routes.rb
Rails.application.routes.draw do

 resources :products
 resources :order_items
 resource :carts, only: [:show]
 resources :charges
 root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    
    before_save :set_subtotal
    
    def subtotal
        order_items.collect { |order_item| order_item.valid? ? ( order_item.unit_price * order_item.quantity) : 0 }.sum 
    end 
    
    private
    
    
    def set_subtotal
        self[:subtotal] = subtotal
    end # this method sets the subtotal and saves it
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    before_save :set_unit_price
    before_save :set_total_price
    
    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end
    
    def total_price
        unit_price * quantity
    end
    
    private
    
    def set_unit_price
        self[:unit_price] = unit_price
    end
    
    def set_total_price
        self[:total_price] = quantity * set_unit_price
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include ApplicationHelper
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @order_items = current_order.order_items
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'usd'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def learn
    
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
    def create
        @order = current_order
        @order_item = @order.order_items.new(order_item_params)
        @order.save
        session[:order_id] = @order.id
    end

	def update
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.update_attributes(order_item_params)
		@order_items = @order.order_items
	end

	def destroy
		@order = current_order
		@order_item = @order.order_items.find(params[:id])
		@order_item.destroy
		@order_items = @order.order_items
	end
	
 private
 
    def order_item_params
        params.require(:order_item).permit(:product_id , :quantity)
    end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
    
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:id])
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  private
  
  def product_params
    params.require(:product).permit(:title, :price)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
 def current_order
    if !session[:order_id].nil?
         Order.find(session[:order_id])
    else
        Order.new
    end
 end 
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<% if @order_items.size>0 %>
	<% @order_items.each do |item| %>
		<div class="well">
			<div class="row">
				<div class="col-sm-8">
					<h3><%= item.product.title %></h3>
				</div>
				<div class="col-sm-4">
					<div class="pull-right">
					<%= form_for(item, remote: true) do |f| %>
						<%= f.hidden_field :product_id, value: item.product.id %>
						<h5><%= item.product.price %></h5>
						<div class="form-group">
							<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
						</div>
						<div class="btn-group">
							<%= f.submit "Update Quantity", class: 'btn btn-primary' %>
							<%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger'  %>
						</div>
						<span>Total Price: <%= item.total_price %></span>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% else %>
	
<% end %>

app/views/carts/show.html.erb
<div class="page-header page-header-small clear-filter" filter-color="orange">
            <div class="page-header-image" data-parallax="true" style="background-image: url('http://demos.creative-tim.com/now-ui-kit/assets/img/header.jpg');">
            </div>
            <div class="container">
                <div class="content-center">
                    <h1 class="title text-center">
											Check Out
										</h1>
                    <h3 class="description text-center">
                      Back Soon
                    </h3>
                </div>
            </div>
</div>
<div class="cart_item">
	<%= render "carts/cart_item" %>
</div>
<div class="active cart">
<%= link_to "#{current_order.order_items.size} items in card and price #{current_order.subtotal}", carts_path %>
</div>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key=""
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<div class="page-header clear-filter" filter-color="orange">
    <div class="page-header-image" data-parallax="true" style="background-image: url('http://wallpapercave.com/wp/3xjL9LP.jpg');">
    </div>
    <div class="container">
        <div class="content-center brand">
            <img class="n-logo" src="http://demos.creative-tim.com/now-ui-kit/assets/img/now-logo.png" alt="">
            <h1 class="h1-seo">Web Marketing.</h1>
            <ul class="header-service-list">
              <li>
                BRANDING
              </li>
              <li>
                MARKETING
              </li>
              <li>
                DEVELOPMENT
              </li>
            </ul>
        </div>
    </div>
</div>

<div class="section">
    <div class="container text-center">
      <h2 class="title">The Collection</h2>
      <p class="card-muted-title">Harry Potter - Minimalist Print Collection</p>
      <h5 class="description">
          2150 Times is a results-driven, digital marketing agency specializing in website design,
          mobile app development, and online marketing. 2150 Times’s mission is to create websites
          and digital solutions that help grow businesses online.
        </h5>
        <br  />
        <button class="btn btn-primary btn-lg btn-round hideme">More About Us</button>
    </div>
</div>

<div class="section">
  <h2 class="title text-center">Best Sellers</h2>
  <p class="card-muted-title text-center">Harry Potter - Minimalist Print Collection</p>
  <ul class="bestsellers-card">
    <li>
        <div class="card">
          <img class="card-img-top" src="https://scontent-ort2-2.xx.fbcdn.net/v/t1.0-9/21105555_10155670867852920_539109938448924283_n.jpg?oh=15a23e6a2ea20c9df6ef6e73c1bb761f&oe=5A28D2A9" alt="Card image cap">
          <div class="card-block text-center">
            <ul class="bestsellers-card-info">
              <li class="card-muted-title">
                Minimalist
              </li>
              <li>
                Wizard Prints
              </li>
              <li>
                <span class="badge badge-primary">Book 3</span>
              </li>
              <br />
            </ul>
            <ul class="list-inline bestsellers-card-dimensions">
              <h5 class="no-margin card-muted-title">Dimensions</h5>
              <li class="list-inline-item text-left">
                <h5 class="no-margin description">18"</h5>
              </li>
              <li class="text-right list-inline-item ">
               <h5 class="no-margin description">12"</h5>
              </li>
            </ul>
            <br />
            <br />
            <p class="description">
              $68
            </p>
            <button class="btn btn-primary hideme">
              <!-- <i class="fa fa-bullseye fa-2x" aria-hidden="true"></i> -->
              Add To Cart
            </button>
          </div>
       </div>
    </li>

    <li>
        <div class="card">
          <img class="card-img-top" src="https://scontent-ort2-2.xx.fbcdn.net/v/t1.0-9/21105555_10155670867852920_539109938448924283_n.jpg?oh=15a23e6a2ea20c9df6ef6e73c1bb761f&oe=5A28D2A9" alt="Card image cap">
          <div class="card-block text-center">
            <ul class="bestsellers-card-info">
              <li class="card-muted-title">
                Minimalist
              </li>
              <li>
                Wizard Prints
              </li>
              <li>
                <span class="badge badge-primary">Book 3</span>
              </li>
              <br />
            </ul>
            <ul class="list-inline bestsellers-card-dimensions">
              <h5 class="no-margin card-muted-title">Dimensions</h5>
              <li class="list-inline-item text-left">
                <h5 class="no-margin description">18"</h5>
              </li>
              <li class="text-right list-inline-item ">
               <h5 class="no-margin description">12"</h5>
              </li>
            </ul>
            <br />
            <br />
            <p class="description">
              $68
            </p>
            <button class="btn btn-primary hideme">
              <!-- <i class="fa fa-bullseye fa-2x" aria-hidden="true"></i> -->
              Add To Cart
            </button>
          </div>
       </div>
    </li>
  </ul>
</div>

<div class="section">
    <div class="container text-center">
      <h2 class="title">Special Print</h2>
      <p class="card-muted-title text-center">Harry Potter - Minimalist Print Collection</p>
      <h5 class="description">
          2150 Times is a results-driven, digital marketing agency specializing in website design,
          mobile app development, and online marketing. 2150 Times’s mission is to create websites
          and digital solutions that help grow businesses online.
        </h5>
    </div>
</div>



<% @products.each do |product| %>
	<div class="card">
		<div class="row">
			<div class="col-sm-8">
				<h3><%= product.title %></h3>
			</div>
			<div class="col-sm-4">
				<div class="pull-right">
				<%= form_for(@order_item, remote: true) do |f| %>
					<%= f.hidden_field :product_id, value: product.id %>
					<h5><%= product.price %></h5>
					<div class="form-group">
						<%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' %>
					</div>
					<%= f.submit "Add to cart", class: 'btn btn-primary btn-sm' %>
				<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/home/learn.html.erb
<div class="page-header page-header-small clear-filter" filter-color="orange">
            <div class="page-header-image" data-parallax="true" style="background-image: url('http://demos.creative-tim.com/now-ui-kit/assets/img/header.jpg');">
            </div>
            <div class="container">
                <div class="content-center">
                    <h1 class="title text-center">Our Services</h1>
                    <h3 class="description text-center">
                      From A to Z.
                    </h3>
                </div>
            </div>
</div>

<div class="section">
    <div class="container text-left">
      <p class="card-muted-title">Harry Potter - Minimalist Print Collection</p>
      <h2 class="title">The Collection</h2>
      <h5 class="description">
          2150 Times is a results-driven, digital marketing agency specializing in website design,
          mobile app development, and online marketing. 2150 Times’s mission is to create websites
          and digital solutions that help grow businesses online.
        </h5>
        <br  />
        <button class="btn btn-primary btn-lg btn-round hideme">More About Us</button>
    </div>
</div>

<div class="section">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="container">
        <h5 class="description">
            2150 Times is a results-driven, digital marketing agency specializing in website design,
            mobile app development, and online marketing. 2150 Times’s mission is to create websites
            and digital solutions that help grow businesses online.
        </h5>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="container text-left">
        <h2 class="card-muted-title">Durability</h2>
        <h2 class="title">Minimalist design printed on high quality aluminum</p>
        <h5 class="description">
            2150 Times is a results-driven, digital marketing agency specializing in website design,
            mobile app development, and online marketing. 2150 Times’s mission is to create websites
            and digital solutions that help grow businesses online.
        </h5>
          <br  />
      </div>
    </div>
  </div>

</div>

<div class="section">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="container">
        <div class="container text-left">
          <h2 class="card-muted-title">Design</h2>
          <h2 class="title">All-Metal Design</h2>
          <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
          </h5>
          <br  />
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="container text-left">
        <h5 class="description">
            2150 Times is a results-driven, digital marketing agency specializing in website design,
            mobile app development, and online marketing. 2150 Times’s mission is to create websites
            and digital solutions that help grow businesses online.
        </h5>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="container">
        <div class="container text-left">
          <p class="card-muted-title">Water - Dust Resistant</p>
          <h2 class="title">A Gift that lasts</h2>
          <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
          </h5>
          <br  />
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="container text-left">
        <h5 class="description">
            2150 Times is a results-driven, digital marketing agency specializing in website design,
            mobile app development, and online marketing. 2150 Times’s mission is to create websites
            and digital solutions that help grow businesses online.
        </h5>
      </div>
    </div>
  </div>
</div>


<div class="section">
    <div class="container text-left">
      <div class="row">
        <div class="col-12 col-md-6">
          <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
          </h5>
        </div>
        <div class="col-12 col-md-6">
          <div class="container text-left">
            <p class="card-muted-title">water and dust resistant</p>
            <h2 class="title">Durable prints to make lasting Gifts</h2>
            <h5 class="description">
                The most durable and elegant harry potter print. front and back metal
                with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
                band.
            </h5>
            <br  />
          </div>
        </div>
      </div>
    </div>
</div>

<div class="section">
    <div class="container text-left">
      <div class="row">
        <div class="col-12 col-md-6">
          <p class="card-muted-title">Dimensions</p>
          <h2 class="title">Perfect fit for walls,  halls, night stand</h2>
          <p class="description">12 Inches x 18 Inches</p>
          <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
          </h5>
          <br  />
        </div>
        <div class="col-12 col-md-6">
          <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
          </h5>
        </div>
      </div>
    </div>
</div>

<div class="section">
    <div class="container text-left">
      <div class="row">
          <div class="col-12 col-sm-6">
            <h5 class="description">
              The most durable and elegant harry potter print. front and back metal
              with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
              band.
            </h5>
          </div>
          <div class="col-12 col-sm-6">
            <p class="card-muted-title">3D Printing</p>
            <h2 class="title">Where minimalist design and 3D meets</h2>
            <h5 class="description">
                The most durable and elegant harry potter print. front and back metal
                with brush aluminum finish. A color‑matched, aerospace‑grade aluminum
                band.
            </h5>
            <br  />
          </div>
      </div>
    </div>
</div>

app/views/layouts/_cart.html.erb
<a href="/carts" class="nav-links">
  <span class="badge badge-default"><%="#{current_order.order_items.size}" %></span>items
  <span class="badge badge-default"> $ <%=  "#{current_order.subtotal}" %></span>
  <i class="fa fa-opencart" aria-hidden="true"></i>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <%= csrf_meta_tags %>

    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no" name="viewport">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700');
    </style>
    <!-- Navbar Start -->
    <!-- Navbar Start -->
    <nav class="navbar navbar-toggleable-md bg-primary fixed-top navbar-transparent " color-on-scroll="500">
            <div class="container">
                <div class="dropdown button-dropdown">
                    <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                        <span class="button-bar"></span>
                        <span class="button-bar"></span>
                        <span class="button-bar"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-header">Dropdown header</a>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">One more separated link</a>
                    </div>
                </div>
                <div class="navbar-translate">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                    <%= link_to "2150 Times", root_path, :class => "navbar-brand" %>
                </div>
                <ul class="nav">
                  <li class="nav-item">
                    <%= render '/layouts/cart' %>
                  </li>
                  <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                  </li> -->
                </ul>
                <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="http://demos.creative-tim.com/now-ui-kit/assets/img/blurred-image-1.jpg">

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <%= link_to "Home", root_path, :class => "nav-link" %>
                        </li>
                        <li class="nav-item">
                          <a href="/static_pages/index" class="nav-link"> Our Services</a>
                        </li>
                        <li class="nav-item">
                          <a href="/static_pages/portfolio" class="nav-link"> Our Portfolio</a>
                        </li>
                        <li class="nav-item">
                          <a href="/static_pages/contact" class="nav-link"> Contact us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link twitter-sharrre-nav" rel="tooltip" title="Tweet" data-placement="bottom" href="#pablo">
                                <i class="fa fa-twitter"></i>
                                <p class="hidden-lg-up">Twitter</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link facebook-sharrre-nav" rel="tooltip" title="Share" data-placement="bottom" href="#pablo">
                                <i class="fa fa-facebook-square"></i>
                                <p class="hidden-lg-up">Facebook</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link linkedin-sharrre-nav" rel="tooltip" title="Share" data-placement="bottom" href="#pablo">
                                <i class="fa fa-linkedin"></i>
                                <p class="hidden-lg-up">LinkedIn</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <!-- Nav Bar End -->


  <div class="wrapper">
    <%= yield %>
  </div>

  <footer class="footer">
        <div class="container">
          <div id="accordion" role="tablist" aria-multiselectable="true">
            <div class="card">
              <div class="card-header" role="tab" id="headingOne">
                <h5 class="mb-0">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Learn and Shop
                  </a>
                </h5>
              </div>

              <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="card-block">
                  Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            Copyright 2017. All rights reserved
          </div>
        </div>
  </footer>
  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
	alert("Invalid")
<% else %>
	$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/order_items/update.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/products/_form.html.erb
<%= form_for(@product) do |f|%>
<div class="form-group">
    <%= f.label :title, "Name" %>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
    <%= f.label :price, "Price" %>
    <%= f.text_field :price, class: 'form-control' %>
</div>

<%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/new.html.erb
<h1>Add New Products</h1>
<%= render 'form' %>